swagger: '2.0'
info:
  title: 'API Documentation for Books'
  description: 'API endpoints to manage Books'
  version: '1.0'
paths:
  /api/book/{bookid}:
    get:
      summary: 'Get a specific book by ID'
      parameters:
        - name: bookid
          in: path
          required: true
          type: integer
          description: 'ID of the book to retrieve'
      responses:
        200:
          description: 'Returns the details of the requested book'
          schema:
            type: 'object'
            properties:
              bookid:
                type: 'integer'
                example: 1
              bookname:
                type: 'string'
                example: 'Flask Programming'
              author:
                type: 'string'
                example: 'John Doe'
              price:
                type: 'integer'
                example: 25
        404:
          description: 'Book not found'
