swagger: '2.0'
info:
  title: 'API Documentation for Books'
  description: 'API endpoints to manage Books'
  version: '1.0'
paths:
  /api/book:
    get:
      summary: 'Get all books'
      responses:
        200:
          description: 'Returns a list of all books'
          schema:
            type: 'array'
            items:
              type: 'object'
              properties:
                bookid:
                  type: 'integer'
                  example: 1
                bookname:
                  type: 'string'
                  example: 'Flask Programming'
                author:
                  type: 'string'
                  example: 'John Doe'
                price:
                  type: 'integer'
                  example: 25
