swagger: '2.0'
info:
  title: 'API Documentation for Books'
  description: 'API endpoints to manage Books'
  version: '1.0'
paths:
  /api/book/{bookid}:
    put:
      summary: 'Update an existing book'
      consumes:
        - application/json
      parameters:
        - name: bookid
          in: path
          required: true
          type: integer
          description: 'ID of the book to update'
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              bookname:
                type: string
                example: 'Python Advanced'
              author:
                type: string
                example: 'John Doe'
              price:
                type: integer
                example: 35
      responses:
        200:
          description: 'Book updated successfully'
          schema:
            type: 'object'
            properties:
              bookid:
                type: 'integer'
                example: 1
        404:
          description: 'Book not found'
