swagger: '2.0'
info:
  title: CRUD API for Books
  description: API endpoints to perform CRUD operations on Books
  version: '1.0'
paths:
  /api/book/:
    post:
      summary: Add a new book
      parameters:
        - in: body
          name: body
          description: Book object
          required: true
          schema:
            type: object
            properties:
              bookname:
                type: string
              author:
                type: string
              price:
                type: integer
      responses:
        201:
          description: Book added successfully
          schema:
            type: object
            properties:
              bookid:
                type: integer
        400:
          description: Bad request, invalid input
      tags:
        - Books
