swagger: '2.0'
info:
  title: CRUD API for Books
  description: API endpoints to perform CRUD operations on Books
  version: '1.0'
paths:
  /api/book/{bookid}:
    delete:
      summary: Delete a book by ID
      parameters:
        - name: bookid
          in: path
          required: true
          type: integer
          description: ID of the book to delete
      responses:
        204:
          description: Book deleted successfully
        404:
          description: Book not found
      tags:
        - Books
