swagger: '2.0'
info:
  title: CRUD API for Books
  description: API endpoints to perform CRUD operations on Books
  version: '1.0'
paths:
  /api/book/:
    get:
      summary: Retrieve all books
      responses:
        200:
          description: List of books
          schema:
            type: array
            items:
              type: object
              properties:
                bookid:
                  type: integer
                bookname:
                  type: string
                author:
                  type: string
                price:
                  type: integer
      tags:
        - Books
